# Generated by Django 4.1 on 2022-08-04 03:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='empty')),
                ('image', models.ImageField(upload_to='posters')),
                ('description', models.TextField()),
                ('release', models.DateField()),
                ('cast', models.ManyToManyField(to='web.castmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.categorymodel')),
                ('language', models.ManyToManyField(to='web.languagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='RequestMovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('480px', '480px'), ('720px', '720px'), ('1080px', '1080px')], default='480px', max_length=10)),
                ('url', models.URLField(blank=True, max_length=1000000, null=True)),
                ('shrink_url', models.URLField(blank=True, max_length=10000, null=True)),
                ('movie', models.ForeignKey(default=web.models.latestMovie, on_delete=django.db.models.deletion.CASCADE, to='web.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshots', models.ImageField(upload_to='screenshots')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.moviemodel')),
            ],
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='tags',
            field=models.ManyToManyField(to='web.tagsmodel'),
        ),
    ]
